apiVersion: v2
name: fineract-extended
description: A Helm chart for extending fineract
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: fin-engine
    repository: "https://fynarfin.io/images/fineract/fin-engine-1.1.0-SNAPSHOT"
    version: 1.1.0-SNAPSHOT